LIST P=16F876A
INCLUDE <P16F876A.INC>

; 사용할 레지스터 지정
PCL	EQU	02H
STATUS	EQU	03H
PORTA	EQU	05H
PORTB	EQU	06H
PORTC	EQU	07H
W_TEMP	EQU	20H
STATUS_TEMP	EQU	21H
NUMBER	EQU	22H
D_1S	EQU	23H
D_10S	EQU	24H
D_100S	EQU	25H
D_1000S	EQU	26H
CNT_DISPLAY	EQU	28H
INTCON	EQU	0BH
TRISA	EQU	85H
TRISB	EQU	86H
TRISC	EQU	87H
ADCON1	EQU	9FH

;사용할 레지스터 지정
W	EQU	B'0'
;메인

ORG		0
	GOTO		START
;인터럽스 
ORG		4
	MOVWF		W_TEMP
	SWAPF		STATUS,W
	MOVWF		STATUS_TEMP
	CALL		DISPLAY
	SWAPF		STATUS_TEMP,W
	MOVWF		STATUS
	SWAPF		W_TEMP,1
	SWAPF		W_TEMP,W
	BCF		INTCON,2
	RETFIE

DISPLAY ;
	
CHECK1	BTFSS		CNT_DISPLAY,1
	GOTO		CHECK2 
	BTFSS		CNT_DISPLAY,0
	GOTO		DISPLAY2
	GOTO		DISPLAY1
	
CHECK2	BTFSS		CNT_DISPLAY,0
	GOTO		DISPLAY4
	GOTO		DISPLAY3

;scanning 방식으로 segment에 출력을 하도록 함

DISPLAY1 ; 1000의 자리에 숫자를 출력하게 함
	MOVLW		0FFH
	MOVWF		PORTB
	CALL		CLEAR_DG
	MOVF		D_1000S,W
	CALL		CONV_BRIDGE
	CALL		DG1
	INCF		CNT_DISPLAY
	RETURN
	
DISPLAY2; 100의 자리에 숫자를 출력하게 함
	MOVLW		0FFH
	MOVWF		PORTB
	CALL		CLEAR_DG
	MOVF		D_100S,W
	CALL		CONV_BRIDGE
	CALL		DG2
	INCF		CNT_DISPLAY
	RETURN


DISPLAY3 ; 10의 자리에 숫자를 출력하게 함
	MOVLW		0FFH
	MOVWF		PORTB
	CALL		CLEAR_DG
	MOVF		D_10S,W
	CALL		CONV_BRIDGE
	CALL		DG3
	INCF		CNT_DISPLAY
	RETURN

DISPLAY4 ; 1의 자리에 숫자를 출력하게 함
	MOVLW		0FFH
	MOVWF		PORTB
	CALL		CLEAR_DG
	MOVF		D_1S,W
	CALL		CONV_BRIDGE
	CALL		DG4
	INCF		NUMBER,1
	INCF		CNT_DISPLAY
	RETURN
	
CONV_BRIDGE ; 바로 CONV를 불러 오면 오류가 생기므로 다리 역할을 해서 CONV로 가게함
   GOTO   CONV
   RETURN


CLEAR_DG ; 모든 자리 수를 set시켜줌, 한번 꺼주어야 정확한 값을 받아 올 수 있기 때문에
   BSF   PORTA, 3
   BSF   PORTA, 2
   BSF   PORTB, 2
   BSF   PORTB, 1
   RETURN
   
DG1 ;1000의 자리 수 출력
   BCF   PORTA, 3
   BSF   PORTA, 2
   BSF   PORTB, 2
   BSF   PORTB, 1
   RETURN
   
DG2 ;100의 자리 수 출력
   BSF   PORTA, 3
   BCF   PORTA, 2
   BSF   PORTB, 2
   BSF   PORTB, 1
   RETURN
   
DG3 ;10의 자리 수 출력
   BSF   PORTA, 3
   BSF   PORTA, 2
   BCF   PORTB, 2
   BSF   PORTB, 1
   RETURN

DG4 ;1의 자리 수 출력
   BSF   PORTA, 3
   BSF   PORTA, 2
   BSF   PORTB, 2
   BCF   PORTB, 1
   RETURN
   
	


START ;포트 지정
	BSF		STATUS,5
	MOVLW		B'00000111'
	MOVWF		ADCON1
	MOVLW		B'00000000'
	MOVWF		TRISA	
	MOVLW		B'00000000'
	MOVWF		TRISC
	MOVWF		TRISB
	
	MOVLW		B'00000010'	
	MOVWF		OPTION_REG
	BCF		STATUS,5
	BSF		INTCON,5
	BSF		INTCON,7
	GOTO		MAIN

MAIN ; 
	MOVLW		00H
	MOVWF		CNT_DISPLAY
	MOVWF		NUMBER
	MOVWF		D_1000S
	MOVWF		D_100S
	MOVWF		D_10S
	MOVWF		D_1S
	MOVLW		0FFH
	MOVWF		PORTA
	BSF		PORTB,3
	
AGAIN	BTFSC		PORTB,3 ;start 버튼 누르면 타이머가 작동하기 시작
	GOTO		AGAIN

LOOP1
	MOVLW		.244

	SUBWF		NUMBER,W
	BTFSS		STATUS,Z
	GOTO		LOOP1

LOOP2 
	CLRF		NUMBER
	INCF		D_1S
	MOVLW		.10
	SUBWF		D_1S,W
	BTFSS		STATUS,Z
	GOTO		LOOP3
	
	CLRF		D_1S
	INCF		D_10S
	MOVLW		.10
	SUBWF		D_10S,W
	BTFSS		STATUS,Z
	GOTO		LOOP3
	
	CLRF		D_10S
	INCF		D_100S
	MOVLW		.10
	SUBWF		D_100S,W
	BTFSS		STATUS,Z
	GOTO		LOOP3

	CLRF		D_100S
	INCF		D_1000S
	MOVLW		.10
	SUBWF		D_1000S,W
	BTFSC		STATUS,Z
	CLRF		D_1000S
	GOTO		LOOP3
	
LOOP3 ; 버튼을 누르면 reset이 되어서 main문으로 다시 돌아가게 됨
	BTFSS		PORTB,4
	GOTO		MAIN
	GOTO		LOOP1
	

CONV ; segment에 출력할 값 불러 옴
   ANDLW   0FH
   ADDWF   PCL, 1

   GOTO   SEG0
   GOTO   SEG1
   GOTO   SEG2
   GOTO   SEG3
   GOTO   SEG4
   GOTO   SEG5
   GOTO   SEG6
   GOTO   SEG7
   GOTO   SEG8
   GOTO   SEG9

;SEGMENT 0~9 숫자 출력
SEG0
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'11100111'
   MOVWF   PORTC
   BCF   	 PORTA, 1
   BCF   	 PORTA, 0
   RETURN
   
SEG1
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'01100000'
   MOVWF   PORTC
   BCF     PORTA, 1
   BCF     PORTA, 0
   RETURN
   
SEG2
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'11000011'
   MOVWF   PORTC
   BSF   PORTA, 1
   BCF   PORTA, 0
   RETURN



SEG3
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'11100010'
   MOVWF   PORTC
   BSF   PORTA, 1
   BCF   PORTA, 0
   RETURN


SEG4
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'01100100'
   MOVWF   PORTC
   BSF   PORTA, 1
   BCF   PORTA, 0
   RETURN

SEG5
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'10100110'
   MOVWF   PORTC
   BSF   PORTA, 1
   BCF   PORTA, 0
   RETURN
    
SEG6
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'10100111'
   MOVWF   PORTC
   BSF   PORTA, 1
   BCF   PORTA, 0
   RETURN
  
SEG7
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'11100000'
   MOVWF   PORTC
   BCF   PORTA, 1
   BCF   PORTA, 0
   RETURN

SEG8
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'11100111'
   MOVWF   PORTC
   BSF   PORTA, 1
   BCF   PORTA, 0
   RETURN
    
SEG9
   MOVLW   B'00000000'
   MOVWF   PORTC
   MOVLW   B'11100110'
   MOVWF   PORTC
   BSF   PORTA, 1
   BCF   PORTA, 0
   RETURN
   
END
 